---

#
# Nur die simplen Datei-Updates, ohne Applikation Code und Neustart etc.
#

# - import_playbook: handlers.yml

- hosts: all
  become_user: root
  become: true
  roles:
    - common
  vars_files:
    - ./site/via_{{instanceName}}.yml
    - vars_common.yml
  # vars:
  #   remoteUser: "{{via_user}}"
  #   stoneName: "{{via.siteName}}"
  environment:
    GS_HOME: /opt/GsDevKit_home
    PATH: /opt/GsDevKit_home/bin:{{ ansible_env.PATH }}

  tasks:

  - import_tasks: tasks_git_update.yml    

  - import_tasks: tasks_common.yml

  - import_tasks: tasks_common_end.yml
