---

- name: restart PHP
  service:
    name: php8.1-fpm
    enabled: yes
    state: restarted

- name: restart nginx
  service:
    name: nginx
    enabled: yes
    state: restarted

- name: restart haproxy
  service:
    name: haproxy
    enabled: yes
    state: restarted

- name: restart monit
  service:
    name: monit
    enabled: yes
    state: reloaded #dont restarted
    use: sysvinit

- name: create postfix aliases
  shell: newaliases

